powsybl/powsybl-diagram

.github/diagram-demo.svg
README.md
pom.xml

No
doc
There is no README.md
A README.md has been added to explain what is the single line diagram project.
**Other …

Add readme

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactory.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/InternCell.java

- true -> if a pattern of internCell is not identified :

options : exceptionIfPatternNotHandled in InternCell and ImplicitCellDetector :

---

.travis.yml
README.md
appveyor.yml
pom.xml

No
Feature
The single line diagram repo depends on a PowSyBl Core snapshot version.
For better stability and because we intend to release soon single line diagram artifact to Maven central we switch to a PowSyBl Core release …

Switch to powsybl core release (3.0.0)

---

pom.xml
single-line-diagram-distribution/pom.xml

Aggregate Jacoco reports

---

single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/AbstractCgmesLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/AbstractSubstationLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/library/ResourcesComponentLibrary.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/InternCell.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/LegPrimaryBlock.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/SubstationGraph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java

Fix Sonar issues

---

.travis.yml

No
Bug fix.
Something on Travis side has changed and Sonar report push failed.
As recommended by Travis team we have modified the script like this:
https://travis-ci.community/t/deploy-fails-with-aws-signaturedoesnotmatch/5835 …

Fix Travis build (Sonar issue)

---

single-line-diagram-core/pom.xml
single-line-diagram-core/src/main/java-templates/com/powsybl/sld/util/PowsyblSingleLineDiagramVersion.java

No
Feature
An implementation of PowSyBl Version plugin has been added to display git source code revision at runtime.
(if any of the questions/checkboxes don't apply, please delete …

Add PowSyBl version plugin

---

.github/workflows/maven.yml

Bug fix
foo-actions/setup-java seems to be broken.
I forked foo-actions/setup-java in geofjamg/setup-java and fix yaml indentation.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …

Use fixed setup-java plugin

---

single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.xml
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/vlDiag_metadata.json

Adding description for a LINE component in xml components description file:
size (0, 0) and one vertical anchor point (0, 0)
Regeneration of 2 metadata json test resource files
**Does this PR introduce a breaking change or deprecate an …

issue_with_wires_connected_to_feeders

---

single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java

Adding 'Close tab' and 'Close all tabs' menu in the javafx viewer
Correction in the substations reloading from preferences during application start
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …

close_all_tabs_in_javafx_application

---

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/TestSVGWriter.java
single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg
single-line-diagram-core/src/test/resources/substation_optimized.svg

Adding values test before creating the svg arrow objects in insertArrowsAndLabels method
#75 
(if any of the …

arrows_visible_when_no_feeder_values_to_display

---

.github/workflows/maven.yml

No
Feature
Instead of hacked geofjamg/setup-java use official actions/setup-java
(if any of the …

Use standard Java Setup action

---

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/test/resources/zone.svg
single-line-diagram-view/src/main/java/com/powsybl/sld/view/WireHandler.java

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@techrain.eu>
#85 

Fix arrows direction

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphTraversal.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java
single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHorizontal.json
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVertical.json
single-line-diagram-core/src/test/resources/TestCase12GraphVL1.json
single-line-diagram-core/src/test/resources/TestCase12GraphVL2.json
single-line-diagram-core/src/test/resources/TestCase2StackedCell.json
single-line-diagram-core/src/test/resources/TestCase3Coupling.json
single-line-diagram-core/src/test/resources/TestCase4NotParallelel.json
single-line-diagram-core/src/test/resources/TestCase5ShuntHorizontal.json
single-line-diagram-core/src/test/resources/TestCase5ShuntVertical.json
single-line-diagram-core/src/test/resources/TestCase6CouplingNonFlatHorizontal.json
single-line-diagram-core/src/test/resources/TestDefaultFeedersPosition.json
single-line-diagram-core/src/test/resources/TestShiftFeedersPosition.json

isolation of the Graph Transversal Algorithm to be reused for other purposes like Topology calculation

Graph Transversal Isolation

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphTraversal.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/TopologicallyConnectedNodesSet.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/TopologyCalculation.java
single-line-diagram-core/src/test/java/com/powsybl/sld/TestTopologyCalculation.java

Signed-off-by: BenoitJeanson <benoit.jeanson@rte-france.com>

Topology Calculation

---

pom.xml

No
Feature
Parent pom v1 is used.
New parent pom v3 is used.
(if any of the questions/checkboxes don't …

Switch to parent pom v3

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImportPostProcessor.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImportPostProcessorTest.java

No
Feature
PowSyBl core 3.0.0 is used
PowSyBl core 3.1.0 is used
(if any of the questions/checkboxes …

Switch to PowSyBl Core 3.1.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java

Signed-off-by: BenoitJeanson <benoit.jeanson@rte-france.com>

small optimizations in Graph

---

single-line-diagram-core/src/main/java/com/powsybl/sld/SubstationDiagram.java
single-line-diagram-core/src/main/java/com/powsybl/sld/VoltageLevelDiagram.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultNodeLabelConfiguration.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/LabelPosition.java
single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java
single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCaseNoIidm.java
single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/vlDiag_metadata.json
single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java

add possiblity to center labels or display them diagonaly

---

single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/LayoutToCgmesExtensionsConverter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/RawGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Feeder3WTNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/FeederBranchNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/FeederNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/FeederWithSideNode.java
single-line-diagram-core/src/test/java/com/powsybl/sld/TestSVGWriter.java
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHorizontal.json
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVertical.json
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmart.json
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmartHorizontal.json
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmartVertical.json

No
Refactoring
FeederWithSideNode has been added to share more code.
Also transformerSide has been removed because redundant with equipmentId 
(if any of the questions/checkboxes …

Add FeederWithSideNode

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml

NO
Dependency Update
powsybl 3.1.0
powsybl 3.2.0
NO

use powsybl 3.2

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractCell.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Cell.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/substation.svg
single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg
single-line-diagram-core/src/test/resources/substation_optimized.svg
single-line-diagram-core/src/test/resources/vl1.svg
single-line-diagram-core/src/test/resources/vl1_optimized.svg
single-line-diagram-core/src/test/resources/vl2.svg
single-line-diagram-core/src/test/resources/vl2_optimized.svg
single-line-diagram-core/src/test/resources/vl3.svg
single-line-diagram-core/src/test/resources/vl3_optimized.svg
single-line-diagram-core/src/test/resources/vlDiag_metadata.json
single-line-diagram-core/src/test/resources/zone.svg

for each cell gather all elements within a svg group <g><\g>

GroupCellInSVG

---

single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/CgmesSubstationLayout.java
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/LayoutToCgmesDlExporterTool.java
single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/RawGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/AbstractSubstationLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Edge.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Feeder2WTLegNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Feeder3WTLegNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Middle2WTNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/SubstationGraph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/TwtEdge.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHorizontal.json
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVertical.json
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-force-layout/src/main/java/com/powsybl/sld/force/layout/ForceSubstationLayout.java
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmart.json
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmartHorizontal.json
single-line-diagram-force-layout/src/test/resources/TestCase11SubstationGraphSmartVertical.json
single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/DLExporter.java

Move transformers middle point creation in substation diagram

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/Feeder2WTLegNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Feeder3WTLegNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Middle2WTNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Middle3WTNode.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Node.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/util/NominalVoltageDiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologicalStyleProvider.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/util/NominalVoltageStyleTest.java
single-line-diagram-core/src/test/java/com/powsybl/sld/util/TopologicalStyleTest.java
single-line-diagram-core/src/test/resources/substation.svg
single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg
single-line-diagram-core/src/test/resources/substation_optimized.svg
single-line-diagram-core/src/test/resources/vl1.svg
single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg
single-line-diagram-core/src/test/resources/vl1_optimized.svg
single-line-diagram-core/src/test/resources/vl2.svg
single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg
single-line-diagram-core/src/test/resources/vl2_optimized.svg
single-line-diagram-core/src/test/resources/vl3.svg
single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg
single-line-diagram-core/src/test/resources/vl3_optimized.svg
single-line-diagram-core/src/test/resources/zone.svg

Fix topological coloring

---

pom.xml

Signed-off-by: HOMER Etienne <etiennehomer@gmail.com>

up to 3.4.0

---

single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/AbstractTestCaseIidm.java
single-line-diagram-core/src/test/java/com/powsybl/sld/layout/SmartVoltageLevelLayoutFactoryTest.java
single-line-diagram-core/src/test/java/com/powsybl/sld/svg/InitialValueProviderTest.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPosition.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionAdder.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionAdderImpl.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionAdderImplProvider.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionImpl.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionXmlSerializer.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePosition.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePositionAdder.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePositionAdderImpl.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePositionAdderImplProvider.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePositionImpl.java
single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/ConnectablePositionXmlSerializer.java
single-line-diagram-iidm-extensions/src/test/java/com/powsybl/sld/iidm/extensions/BusbarSectionPositionXmlTest.java
single-line-diagram-iidm-extensions/src/test/java/com/powsybl/sld/iidm/extensions/ConnectablePositionXmlTest.java

NO
Feature
Using previous extension API for ConnectablePosition
Using new extension API for ConnectablePosition
(if any of the questions/checkboxes don't apply, please delete them …

Connectableposition

---

single-line-diagram-core/pom.xml
single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java
single-line-diagram-core/src/test/java/com/powsybl/sld/model/AddNodeGraphTest.java

No
Feature
To replace a node by another node, the node needs to be added to the graph and then substituted
A node can be replaced by another node directly by using `Graph.replace` method, which calls `Graph.add` and then `Graph.substitute` …

Replace node

---

pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-color/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

no
feature
Because of 1.5.0 release, we switch to 1.6.0-SNAPSHOT in master branch.

Bump 1.6.0-SNAPSHOT

---

single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-core/src/test/resources/TestCase1BusBreaker.json

https://dev.azure.com/GridSuite/GridStudy/_sprints/backlog/GridStudy%20Team/GridStudy/Sprint%2012?workitem=220
(if any of the questions/checkboxes don't apply, please delete them …

Stop creating useless disconnectors in bus breaker view

---

single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.xml
single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg
single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/substation.svg
single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg
single-line-diagram-core/src/test/resources/substation_optimized.svg
single-line-diagram-core/src/test/resources/vl1.svg
single-line-diagram-core/src/test/resources/vl1_decorated.svg
single-line-diagram-core/src/test/resources/vl1_decorated_opt.svg
single-line-diagram-core/src/test/resources/vl1_lpChanged.svg
single-line-diagram-core/src/test/resources/vl1_lpChanged_opt.svg
single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg
single-line-diagram-core/src/test/resources/vl1_optimized.svg
single-line-diagram-core/src/test/resources/vlDiag_metadata.json
single-line-diagram-core/src/test/resources/zone.svg

No
Bug fix
Glitch on wires at loads (wrong anchor point)

Wires glitch at loads

---

README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-color/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

No
powsybl-core 3.6.0
powsybl-core 3.7.0

Updating PowSyBl Core 3.7.0

---

README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-color/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

No
Feature
We switch to 1.8.0-SNAPSHOT as 1.7.0 has been released
We patch the changes of 1.7.1 as 1.7.1 has been released
No

Patch 1.7.1 changes and bump 1.8.0-SNAPSHOT

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/HorizontalSubstationLayout.java
single-line-diagram-core/src/test/resources/TestCase11SubstationGraphH.json

PR #180 needs to be merge before this PR.
Yes, #182

Extraspace between voltage levels in substation diagrams

---

pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-color/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

N/A
Release
The current version is v1.8.0-SNAPSHOT
The new version is v1.9.0-SNAPSHOT, preparing the next release candidate
(if any of the questions/checkboxes don't apply, please …

Prepare release 1.8.0

---

pom.xml

No
powsybl-core 3.7.0
powsybl-core 3.8.0
No

Updating powsybl-core 3.8.0

---

pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-color/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

No
Feature
We switch to 1.8.0 for releasing it.
No

Bump 1.8.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractPrimaryBlock.java
single-line-diagram-core/src/test/java/com/powsybl/sld/raw/TestIncompleteFeederIssue.java
single-line-diagram-core/src/test/resources/TestIncompleteFeederIssue.json

No
Bug fix
We encounter an exception in case of degenerated and incomplete feeder with no equipment connected.
Exception has been fixed
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …

Fix exception with incomplete feeder

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java
single-line-diagram-core/src/test/java/com/powsybl/sld/model/AddNodeGraphTest.java

No
Bug fix
When replacing a node, new node is not in the map of nodes
When replacing a node, new node is in the map of nodes
No

Replace node bug

---

single-line-diagram-core/src/main/java/com/powsybl/sld/util/DomUtil.java

Yes, #200
This reverts commit 8ce5167005e1c012c07826fc23fad1f233e8ab2b (PR #199).

Avoid security issue due to xml external access (reverts #199)

---

.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

No
Version update
1.9.0-SNAPSHOT version
1.9.0 (first commit) then 2.0.0-SNAPSHOT version (second commit)
No

Release v1.9.0

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologyVisitorId.java
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml

No
Library update
powsybl-core 3.8.0
powsybl-core 4.0.0
No

Update powsybl core 4.0.0

---

.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml
single-line-diagram-view-app/pom.xml
single-line-diagram-view/pom.xml

No
Version update
2.0.0-SNAPSHOT version
2.0.0 (first commit) then 2.1.0-SNAPSHOT version (second commit)

Release v2.0.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/SubstationGraph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/VoltageLevelGraph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/ZoneGraph.java

No
Feature
Graph, SubstationGraph and ZoneGraph are final classes
Graph, SubstationGraph and ZoneGraph are non-final classes and thus can be extended.
No

Non-final graph classes

---

.github/workflows/maven.yml
pom.xml
single-line-diagram-force-layout/pom.xml

No
Bug fix
Exclusions for org.gephi are both in pom.xml and in single-line-diagram-force-layout/pom.xml. These exclusions might not be merged when a dependency on force-layout is added (in powsybl-dev-tools/single-line-diagram-viewer for instance).
All org.gephi exclusions are now in pom.xml.
No

org.gephi exclusions gathered

---

pom.xml

No
powsybl-core 4.0.0
powsybl-core 4.1.0
No

Bump to powsybl-core 4.1.0

---

README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
Version update
2.1.0-SNAPSHOT version
2.1.0 (first commit) then 2.2.0-SNAPSHOT version (second commit)

Release v2.1.0

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-iidm-extensions/pom.xml

Import PowSyBl core pom

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/Position.java

N/A
License
The LFE licensing check report an invalid license header
The license has been fixed

Fix license header

---

pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-core/src/main/java/com/powsybl/sld/library/Components.java

No
powsybl-core 4.1.0
powsybl-core 4.2.0
No

Bump to powsybl-core 4.2.0

---

README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
Version update
2.2.0-SNAPSHOT version
2.2.0 (first commit) then 2.3.0-SNAPSHOT version (second commit)
**Does this PR introduce a breaking change or deprecate an API?** No

Release v2.2.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagramTool.java
single-line-diagram-core/src/main/java/com/powsybl/sld/library/ComponentLibrary.java
single-line-diagram-core/src/main/java/com/powsybl/sld/library/ConvergenceComponentLibrary.java
single-line-diagram-core/src/main/java/com/powsybl/sld/library/ResourcesComponentLibrary.java
single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase12GraphWith3WT.java
single-line-diagram-core/src/test/java/com/powsybl/sld/library/ComponentLibraryTest.java
single-line-diagram-core/src/test/java/com/powsybl/sld/svg/InitialValueProviderTest.java

Component library automatic discovery

---

pom.xml

No
powsybl-core 4.2.0
powsybl-core 4.3.1
No

Bump to powsybl-core 4.3.1

---

README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
Version update
2.3.0-SNAPSHOT version
2.3.0 (first commit) then 2.4.0-SNAPSHOT version (second commit)
**Does this PR introduce a breaking change or deprecate an API?** No

Release v2.3.0

---

single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/AbstractTestCaseIidm.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/raw/AbstractTestCaseRaw.java

No
Feature
The test refererences have to be manually updated when changes occur
The test references are automatically updated if feature enabled in AbstractTestCase
No

Override test references

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLUtils.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/BusDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/BusbarDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/GeneratorDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/HvdcLineDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/LineDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/LoadDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/ShuntDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/SvcDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/SwitchDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/TransformerDiagramDataImporter.java
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/test/java/com/powsybl/sld/cgmes/layout/LayoutToCgmesExtensionsTest.java
single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java
single-line-diagram-iidm-extensions/src/test/resources/branchStatusRef.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml

No
powsybl-core 4.3.1
powsybl-core 4.4.0-RC1
No

Bump powsybl core 4.4.0-RC1

---

pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
Bump version to prepare release
Don't squash the commits

Prepare release candidate 2.4.0

---

pom.xml

No
powsybl-core 4.4.0-RC1
powsybl-core 4.4.0
No

Bump to powsybl-core 4.4.0

---

.github/diagram-demo.svg
.github/example_n.svg
README.md

No
Docs update
README.md outdated
README.md up-to-date
No

Update README.md following 2.4.0 release

---

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/resources/vl1_tooltip_opt.svg

No
Bug fix
NullPointerException if tooltip enabled on null-name nodes
No tooltip added for null-name nodes
No

Fix NullPointerException if tooltip enabled on null-name nodes

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/VoltageLevelGraph.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramLabelProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramLabelProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramStyleProvider.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/ElectricalNodeInfo.java
single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java
single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg
single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg
single-line-diagram-core/src/test/resources/vlDiag_metadata.json

No
Refactor
Electrical node infos are created by DiagramStyleProvider
Electrical node infos are created by DiagramLabelProvider, and their style are retrieved with DiagramStyleProvider
**Does this PR introduce a breaking change or deprecate an API?** Yes!

Refactor electrical node info provider

---

pom.xml

No
Dependency version update
powsybl-core 4.5.0-RC1
powsybl-core 4.5.0

Bump powsybl-core to 4.5.0

---

single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java

Signed-off-by: Thomas ADAM <tadam@silicom.fr>
No
Feature
Debug files are written at user home root folder
Debug files are written at user home .powsybl folder
(if any of the …

Add .powsybl folder to write debug files

---

pom.xml

Bump to powsybl-core 4.5.1

---

single-line-diagram-core/src/main/resources/base-voltages.yml
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestInternalBranchesBusBreaker.java
single-line-diagram-core/src/test/resources/InternalBranchesBusBreaker.svg

No
Bug fix
No embedded default base voltages config file, forcing the user to add its own
If no user defined base voltages config file, the embedded default is loaded
No

Embedded base voltages config file

---

pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
Version update
2.6.0-SNAPSHOT version
2.6.0 (first commit) then 2.7.0-SNAPSHOT version (second commit)
**Does this PR introduce a breaking change or deprecate an API?** No

Prepare release v2.6.0

---

pom.xml

No
Dependency version update
powsybl-core 4.5.1
powsybl-core 4.6.0-RC1
No

Bump powsybl-core to 4.6.0-RC1

---

single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagram.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/SVGWriter.java
single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusNodeBreaker.svg
single-line-diagram-core/src/test/resources/TestSldClassSubstation.svg
single-line-diagram-core/src/test/resources/substation.svg
single-line-diagram-core/src/test/resources/substation_feeder_arrow_symmetry.svg
single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg
single-line-diagram-core/src/test/resources/substation_optimized.svg
single-line-diagram-core/src/test/resources/zone.svg

No
Refactor (API simplification)
SVGWriter interface offers too many similar methods, whereas one would be enough.
Only one method in SVGWriter API, taking a `Graph` and a `Writer`. SVGWriter is meant to be used only through SingleLineDiagram interface, which uses only that single method.

Simpler SVGWriter API

---

single-line-diagram-core/src/main/java/com/powsybl/sld/model/BusNode.java

No
Bug fix
Generated label is printed on fictitious buses
No label if bus is fictitious
No

Remove label on fictitious BusNode

---

single-line-diagram-core/src/main/java/com/powsybl/sld/library/Component.java
single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.json
single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json
single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/vlDiag_metadata.json

No
Cleanup
Duplicate/useless information in components.json
components.json cleaned
No

Cleanup components json

---

.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-force-layout/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.7.0-SNAPSHOT version, README.md refers to 4.4.0 version
2.7.0 version + README.md updated (first commit) then 2.8.0-SNAPSHOT version (second commit)
No

Prepare release v2.7.0

---

pom.xml
single-line-diagram-iidm-extensions/src/test/resources/branchStatusRef.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml

No
Library update
powsybl-core 4.6.0
powsybl-core 4.7.0-RC1
No

Bump powsybl-core to 4.7.0-RC1

---

pom.xml

No
Library update
powsybl-core 4.7.0-RC1
powsybl-core 4.7.0
No

Bump powsybl-core to 4.7.0

---

.github/diagram-demo.svg
.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.8.0-SNAPSHOT version, bug in README.md which refers to 2.6.0 version and 4.7.0 powsybl-core
2.8.0 version + README.md updated (first commit) then 2.9.0-SNAPSHOT version (second commit)
No

Prepare release v2.8.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/TopologicallyConnectedNodesSet.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/TopologyCalculation.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestTopologyCalculation.java

Yes, fixes #196 in another way than suggested
Feature
Extremity criteria in topology calculation cannot be changed
Extremity criteria can be changed and a method to filter the results is provided

Allow to customize topology calculations

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramLabelProvider.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java
single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json
single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json
single-line-diagram-core/src/test/resources/substDiag_metadata.json
single-line-diagram-core/src/test/resources/vl1_tooltip_opt.svg
single-line-diagram-core/src/test/resources/vlDiag_metadata.json

No
Feature
Tooltip content is hard coded (name of the node)
Tooltip content is provided by the DiagramLabelProvider for each Node

Tooltip provider

---

.github/diagram-demo.svg
.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.9.0-SNAPSHOT version, soon outdated README.md which refers to 2.8.0 version
2.9.0 version + README.md updated (first commit) then 2.10.0-SNAPSHOT version (second commit)
No

Prepare release v2.9.0

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml

No
feature
There is no exhaustive dependency management that could be imported in another project like is has been done fore powsybl core.
We can just import sld parent to get consistent version of all SLD artifacts
```xml …
```

Dependency management

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/src/test/java/com/powsybl/sld/cgmes/dl/iidm/extensions/Networks.java

No
Library update
powsybl-core 4.7.0
powsybl-core 4.8.0
No

Bump powsybl-core to 4.8.0

---

.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.10.0-SNAPSHOT version
2.10.0 version + README.md updated (first commit) then 2.11.0-SNAPSHOT version (second commit)
No

Prepare release 2.10.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/builders/NetworkGraphBuilder.java

No
Feature
`NetworkGraphBuild` is hard to extend as there is some internal classes are not public.
`NetworkGraphBuild` is now open for creating custom nodes.
**Does this PR introduce a breaking change or deprecate an API?** *If …

Open NetworkGraphBuilder for custom implementation

---

.github/workflows/maven.yml
pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/AbstractCgmesDLExporterTest.java
single-line-diagram-iidm-extensions/src/test/resources/branchStatusRef.xml
single-line-diagram-iidm-extensions/src/test/resources/busbarSectionPositionRef.xml
single-line-diagram-iidm-extensions/src/test/resources/connectablePositionRef.xml

No
Library update
powsybl-core 4.8.0
powsybl-core 4.9.0
No

Bump powsybl-core to 4.9.0

---

.github/diagram-demo.svg
.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.11.0-SNAPSHOT version
2.11.0 version + README.md updated (first commit) then 2.12.0-SNAPSHOT version (second commit)
No

Prepare release v2.11.0

---

.github/workflows/maven.yml

No
CI changes
CI workflow is triggered on push
CI workflow is triggered on pull request and on push to master or release-v** branches
No

CI workflow trigger updated

---

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramLabelProvider.java

**Does this PR already have an issue describing the problem?** 
Yes, fixes #393

Display equipment id instead of diagram id

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockPositionner.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CalculateCellHeightBlockVisitor.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CalculateCoordBlockVisitor.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CalculateCoordCellVisitor.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CellBlockDecomposer.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LBSCluster.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LegBusSet.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/blocks/BlockVisitor.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/blocks/LegParallelBlock.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/cells/InternCell.java
single-line-diagram-core/src/test/java/com/powsybl/sld/raw/TestUnhandledPatternInternCell.java

No
Refactoring
Duplicate code, typos, dead code
Refactoring the code to fix duplicate code, typos and dead code
No, internal API

Intern cell various refactoring

---

.github/diagram-demo.svg
.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml
single-line-diagram-iidm-extensions/pom.xml

No
2.12.0-SNAPSHOT version
1. first commit: 2.12.0 version + README.md updated + powsybl-core bump to 4.9.1
2. second commit: 2.13.0-SNAPSHOT version
No

Prepare release v2.12.0

---

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramLabelProvider.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/CreateNetworksUtil.java
single-line-diagram-core/src/test/java/com/powsybl/sld/svg/FeederInfoProviderTest.java

No
Bug fix
No flow values are displayed on hvdc
Flow values are now displayed on hvdc
No
Introduced by #388 (before that PR, HVDC were before always seen as injections, and therefore the flow values were displayed)

Add flow values on hvdc feeders

---

.github/diagram-demo.svg
.github/example_n.svg
README.md
pom.xml
single-line-diagram-cgmes/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram-core/pom.xml
single-line-diagram-distribution/pom.xml

No
2.12.0-SNAPSHOT version
1. first commit: 2.13.0 version + README.md updated
2. second commit: 2.14.0-SNAPSHOT version
No

 Prepare release v2.13.0

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImportPostProcessorTest.java
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/AbstractCgmesLayout.java
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/test/java/com/powsybl/sld/cgmes/layout/CgmesZoneLayoutTest.java
single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagramTool.java
single-line-diagram-core/src/main/java/com/powsybl/sld/builders/SubstationRawBuilder.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/HorizontalSubstationLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayout.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/graphs/NodeFactory.java
single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase11SubstationGraph.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase15GraphWithVoltageIndicator.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCaseConsecutiveShunts.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java
single-line-diagram-core/src/test/java/com/powsybl/sld/svg/GraphMetadataTest.java
single-line-diagram-core/src/test/java/com/powsybl/sld/util/NominalVoltageStyleTest.java

No
Technical debt
A new checkstyle rule has been added. 

Upgrade to PowSyBl parent 9

---

pom.xml
single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/LayoutToCgmesDlExporterTool.java
single-line-diagram-core/pom.xml
single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagramTool.java
single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCaseConsecutiveShunts.java

No
Library update
powsybl-core 4.10.0
powsybl-core 5.0.0-RC1
No, not directly.

Bump powsybl-core to 5.0.0-RC1

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/cells/ShuntCell.java

No
Bug fix
Shunt with internal connections leads to an exception to be thrown
Shunt with internal connections are supported
No

Internal connection shunt

---

single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.json
single-line-diagram-core/src/main/resources/ConvergenceLibrary/load-break-switch-closed.svg
single-line-diagram-core/src/main/resources/ConvergenceLibrary/load-break-switch-open.svg
single-line-diagram-core/src/test/resources/TestCaseLoadBreakSwitch.svg

No
Bug fix
Load break switches have always been smaller than switches for no clear reason
Load break switches now have the same size as breakers
No

Bigger load break switch

---

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CalculateCoordCellVisitor.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/blocks/BodyPrimaryBlock.java
single-line-diagram-core/src/main/java/com/powsybl/sld/model/cells/ShuntCell.java
single-line-diagram-core/src/test/resources/consecutive_shunts.svg

No
Bug fix
Shunt width is not properly calculated (too narrow)
Shunt width is properly calculated
No

Shunt width increased

---

.github/diagram-demo.svg
.github/diagram_example.svg
.github/example_n.svg
.github/partial_diagram_example_1_25.svg
.github/partial_diagram_example_25.svg
README.md
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

No
3.0.0-SNAPSHOT version
1. first commit: 3.0.0 version + README.md updated
2. second commit: 3.1.0-SNAPSHOT version
No

Prepare release v3.0.0

---

README.md

Signed-off-by: Sophie Frasnedo <sophie.frasnedo@rte-france.com>
docs update
Small typos
Typos corrected

fix small typos on readme

---

pom.xml

No
Library update
powsybl-core 5.1.0-RC1
powsybl-core 5.1.0
No

Bump powsybl-core to 5.1.0

---

network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java
network-area-diagram/src/test/resources/3wt.svg
network-area-diagram/src/test/resources/3wt_disconnected.svg
network-area-diagram/src/test/resources/3wt_disconnected_topological.svg
network-area-diagram/src/test/resources/3wt_partial.svg
network-area-diagram/src/test/resources/edge_info_double_labels.svg

No
Bug fix / feature
3WT node position is included in cx / cy values
3WT node position is included in translate value
No

[NAD] Translate 3WT node to position

---

diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

No
Version update
3.2.0-SNAPSHOT version
1. first commit: 3.2.0 version
2. second commit: 4.0.0-SNAPSHOT version
No

Prepare 3.2.0 release 

---

distribution-diagram/pom.xml

No
Feature
powsybl-diagram-test not covered by tests according to sonar report
powsybl-diagram-test covered by tests by adding it in powsybl-diagram-distribution
No

Add diagram-test in distribution for cross-module coverage

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

No
Version update
3.3.0-SNAPSHOT version
1. first commit: 3.3.0 version
2. second commit: 4.0.0-SNAPSHOT version
No
**DO NOT** squash the commits

Prepare release v3.3.0

---

diagram-test/src/main/java/com/powsybl/diagram/test/Networks.java
pom.xml

Update powsybl-core version to v5.3.2

---

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/builders/SubstationRawBuilder.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/raw/TestCase11SubstationGraph.java
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRaw.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRaw2.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRaw2With2wts.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRaw2With3wts.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRaw2WithLines.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHRawWithLines.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVRaw.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVRaw2.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVRaw2With2wts.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVRaw2With3wts.json
single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVRaw2WithLines.json

Warn user when trying to use voltagelevel from another substation

---

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/HorizontalSubstationLayout.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestViewBox.java
single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxBB.svg
single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxBT.svg
single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxTB.svg
single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxTT.svg
single-line-diagram/single-line-diagram-core/src/test/resources/network_common_methods_createLine_BB.xiidm
single-line-diagram/single-line-diagram-core/src/test/resources/network_common_methods_createLine_BT.xiidm
single-line-diagram/single-line-diagram-core/src/test/resources/network_common_methods_createLine_TB.xiidm
single-line-diagram/single-line-diagram-core/src/test/resources/network_common_methods_createLine_TT.xiidm

536 viewbox incorrectly specified in some cases depending on the direction of a line between two voltage levels

---

diagram-test/src/main/java/com/powsybl/diagram/test/Networks.java
network-area-diagram/src/test/resources/IEEE_118_bus.svg
network-area-diagram/src/test/resources/IEEE_118_bus_partial.svg
network-area-diagram/src/test/resources/IEEE_118_bus_partial_non_connected.svg
pom.xml

No
Feature
Diagram uses powsybl-core-5.3.2 (and powsybl-parent 13).
Diagram uses powsybl-core 6.0.0 RC1 (and powsybl-parent 15).

Bump to powsybl core 6.0.0-RC1

---

pom.xml

Bump to powsybl-core v6.0.0

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Bump to v4.0.0 and v4.1.0-SNAPSHOT

Release v4.0.0

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Bump to v4.1.0 and v4.2.0-SNAPSHOT

Release v4.1.0

---

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphRefiner.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactoryParameters.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DirectionalFeederInfo.java

Fix Javadoc warnings

---

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/zonebygrid/README.md

Matrix Zone diagram (multiple substations) : documentation update

---

pom.xml

Bump to powsybl-core v6.2.0

---

single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/CgmesZoneLayoutFactory.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagram.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/SldParameters.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/HorizontalZoneLayoutFactory.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/MatrixZoneLayoutFactory.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/VerticalZoneLayoutFactory.java
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ZoneLayoutFactory.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/SldParametersTest.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase13ZoneGraph.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/raw/TestCase12ZoneGraph.java

Refactor ZoneLayoutFactory

---

pom.xml

Bump to powsybl-core v6.2.4

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Bump to v4.3.0 and v4.4.0-SNAPSHOT

Release v4.3.0

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Prepare next release 4.4.0
4.4.0-SNAPSHOT version
4.4.0 (first commit) then 4.5.0-SNAPSHOT (2nd commit)
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified

Prepare release v4.4.0

---

network-area-diagram/src/main/java/com/powsybl/nad/build/iidm/VoltageLevelFilter.java

VoltageLevelFilter's getVoltageLevels function is now public
n/a

VoltageLevelFilter's getVoltageLevels function is now public

---

pom.xml

Bump to powsybl-core v6.4.0-RC2

Bump to powsybl-core 6.4.0-RC2

---

pom.xml

Bump to powsybl-core v6.4.0

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Prepare next release 4.5.0
4.5.0-SNAPSHOT version
4.5.0 (first commit) then 4.6.0-SNAPSHOT (2nd commit)
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified

Prepare v4.5.0 release

---

pom.xml

Dependency update
powsybl-core 6.4.0
powsybl-core 6.4.1
powsybl-core 6.4.0 should not be used as it brought inconsistencies which are fixed in powsybl-core 6.4.1

Bump powsybl-core to 6.4.1

---

network-area-diagram/src/main/java/com/powsybl/nad/layout/AbstractLayout.java
network-area-diagram/src/main/java/com/powsybl/nad/model/BusNode.java
network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java
network-area-diagram/src/main/java/com/powsybl/nad/svg/iidm/TopologicalStyleProvider.java
network-area-diagram/src/test/resources/IEEE_57_bus.svg

Restore natural bus order for css nad

---

README.md

No
Docs update.
In the README.md, the links point to the powsybl.org website.
The readthedocs for the tutorials being available, I changed the links. 

Modify links in README.md to the tutorial readthedocs documentation.

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/iidm/HighlightLineStateStyleProvider.java
single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseFictitiousBus.svg

Prepare next release 4.6.1 on release-v4.6.0 branch
4.6.0 version
1. v4.6.1-SNAPSHOT (first commit)
2. Fix bug on fictitious busNodes (#654)
3. v4.6.1 (last commit)
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the release commit verified

Prepare patch release v4.6.1

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml
single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/iidm/HighlightLineStateStyleProvider.java
single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCaseBusDisconnected.java
single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseBusBreakerBusConnected.svg
single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseNodeBreakerBbsConnected.svg

Prepare next release 4.6.2 on release-v4.6.0 branch
4.6.1 version
1. v4.6.2-SNAPSHOT (first commit)
2. Fix disconnected bus in bus breaker topology (#657)
3. v4.6.2 (last commit)
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the release commit verified

Prepare patch release v4.6.2

---

pom.xml

No
Library update
powsybl-core 6.5.0
powsybl-core 6.6.0-RC1

Bump powsybl-core to 6.6.0-RC1

---

pom.xml

No
Library update
powsybl-core 6.6.0-RC1
powsybl-core 6.6.0

Bump powsybl-core to v6.6.0

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Prepare next release 4.7.0
4.7.0-SNAPSHOT version
4.7.0 (first commit) then 4.8.0-SNAPSHOT (2nd commit)
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified

Prepare v4.7.0 release

---

diagram-test/pom.xml
diagram-util/pom.xml
distribution-diagram/pom.xml
network-area-diagram/pom.xml
pom.xml
single-line-diagram/pom.xml
single-line-diagram/single-line-diagram-cgmes/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml
single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml
single-line-diagram/single-line-diagram-core/pom.xml

Prepare next release 4.8.0
4.8.0-SNAPSHOT version
4.78.0 (first commit) then 4.9.0-SNAPSHOT (2nd commit)
⚠️ DO NOT squash the commits
⚠️ Merge branch on main with fast-forward locally, then push, in order to keep the commits verified

Prepare v4.8.0 release

---

.github/workflows/maven.yml
.gitignore
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

No
Feature
No maven wrapper supplied
Maven wrapper is now available

Add maven wrapper
