powsybl/powsybl-diagram

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramInitialValueProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/InitialValue.java, single-line-diagram-core/src/test/java/com/powsybl/sld/svg/InitialValueProviderTest.java, single-line-diagram-core/src/test/resources/TestCase1.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHorizontal.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHorizontalNominalVoltageLevel.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphVertical.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL1.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL1_optimized.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL2.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL2_optimized.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL3.svg, single-line-diagram-core/src/test/resources/TestCase12GraphVL3_optimized.svg, single-line-diagram-core/src/test/resources/TestCase1BusBreaker.svg, single-line-diagram-core/src/test/resources/TestCase1inverted.svg, single-line-diagram-core/src/test/resources/TestCase2StackedCell.svg, single-line-diagram-core/src/test/resources/TestCase4NotParallelel.svg, single-line-diagram-core/src/test/resources/TestCase5ShuntHorizontal.svg, single-line-diagram-core/src/test/resources/TestCase5ShuntVertical.svg, single-line-diagram-core/src/test/resources/TestDefaultFeedersPosition.svg, single-line-diagram-core/src/test/resources/TestDefaultFeedersPosition2.svg, single-line-diagram-core/src/test/resources/TestShiftFeedersPosition.svg, single-line-diagram-core/src/test/resources/TestSubstation.svg, single-line-diagram-core/src/test/resources/TestUnicityNodeIdNetWork1.svg, single-line-diagram-core/src/test/resources/TestUnicityNodeIdNetWork2.svg, single-line-diagram-core/src/test/resources/TestVL.svg, single-line-diagram-core/src/test/resources/nominalVoltage.svg, single-line-diagram-core/src/test/resources/substDiag.svg, single-line-diagram-core/src/test/resources/topological.svg, single-line-diagram-core/src/test/resources/vlDiag.svg
Providing an initial value for a dangling line, which was missing
Correction in providing an initial value for a load : we now get the calculated P and Q values from the terminal
Regenerating the svg test cases files
**Does this PR …
=> missing_initial_values_for_dangling_lines

single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java
Not displaying the grid if the node buses positions are not calculated by
the choosen layout (Random, CGMES ...)
(if …
=> weird_grid_display_behaviour

single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/CgmesVoltageLevelLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/HorizontalSubstationLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/InfoCalcPoints.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/VerticalSubstationLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Graph.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Node.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestShiftFeedersPosition.java, single-line-diagram-core/src/test/resources/TestShiftFeedersPosition.json
Moving the shift feeders height functionality from SVGWriter processing to the layout application processing
Saving the initial feeder node height during the height shifting process
Changing the computation of the snake lines coordinates (we need to use both old and new height feeder node position)
**What is the current behavior?** *(You can also link to an open issue …
=> correction_shift_feeders

single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImportPostProcessor.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImportPostProcessorTest.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLModelTest.java
Signed-off-by: Christian Biasuzzi <christian.biasuzzi@techrain.eu>
#79 
bug fix
#79 
=> don't query the tstore for DL data,  when the DL profile is missing

single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/AbstractCouplingDeviceDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/AbstractInjectionDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/GeneratorDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/LoadDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/ShuntDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/SvcDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/SwitchDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/importers/TransformerDiagramDataImporter.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/AbstractCgmesDLTest.java, single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/CgmesDLImporterTest.java
Signed-off-by: massimo.ferraro <massimo.ferraro@techrain.eu>
Bug fix
Part of the DL data is not correctly imported in the IIDM extensions when there are multiple diagrams 
(if any …
=> Fix DL import of multiple diagrams

single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/postprocessor/GraphBuildPostProcessor.java, single-line-diagram-core/src/main/java/com/powsybl/sld/postprocessor/GraphBuildPostProcessorMock.java
No
Feature
There is no way to access network model from graph post processor.
An additional parameter as been added to GraphBuildPostProcessor.addNode to get access to original network model.
**Does this PR introduce a …
=> Access to network model from graph post processor

single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/resources/CGMES-DL.sparql
Bug fix
without this fix, CGMES' ProtectedSwitch is not included in DL import queries as a kind of switch
(if any of the questions/checkboxes don't apply, please delete them …
=> fixes cgmes-dl sparql queries, to include ProtectedSwitches

pom.xml
We must absolutely merge this before the next release
NO
Bug Fix
if we do a release, no aggregated javadoc
aggregated javadoc
NO
=> fix aggregated javadoc for release + remove obsolete properties

single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagramTool.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Fictitious3WTNode.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/NominalVoltageDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologicalStyleProvider.java, single-line-diagram-core/src/test/java/com/powsybl/sld/NominalVoltageStyleTest.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestCase11SubstationGraph.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestCase12GraphWith3WT.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestSVGWriter.java, single-line-diagram-core/src/test/resources/TestCase12GraphVL1.json, single-line-diagram-core/src/test/resources/TestCase12GraphVL2.json, single-line-diagram-core/src/test/resources/TestCase12GraphVL3.json, single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java
Removing all iidm class references in DefaultDiagramStyleProvider class (network, three windings transformer, voltage level), by adding the necessary informations in the fictitious 3WT node class, during the graph building phase.
Modification of some of the test cases subsequently.
**What is the …
=> removing_iidm_network_references_in_default_diagram_style_provider

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestSVGWriter.java, single-line-diagram-core/src/test/resources/zone.svg
Moving the svg transformers components rotation from default style provider methods to the default svg writer class
Correction in the zone test case (the 2 windings transformer svg in the first substation was not rotated)
**Does this PR …
=> svg_transformers_rotation_in_svg_writer

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/HorizontalLane.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/LBSCluster.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/LBSClusterSide.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/LegBusSet.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/Link.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/Links.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/PositionByClustering.java
No
Bug fix
Voltage level layout "position by clustering" is not stable, so different call to layout could end up to different positions and so on a different SVG.
All HashSet and HashMap have been replaced by LinkedHashSet …
=> Improve position layout by clustering stability

single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java, single-line-diagram-core/src/test/java/com/powsybl/sld/TestCase1BusBreaker.java, single-line-diagram-core/src/test/resources/TestCase1BusBreaker.json
No
Bug fix
For bus/breaker topology, switches (couplers) are not taken into account in voltage level graph build. 
For bus/breaker topology, switches (couplers) are now correctly processed.
**Does this PR introduce a breaking …
=> Missing switches in bus/breaker topo

.github/workflows/maven.yml, pom.xml
No
feature
JavaFX viewer modules are compiled by default. 
A 'viewer' profile has to be activated to compile JavaFX viewer. …
=> Create a viewer profile to not compile by default JavaFX viewer

single-line-diagram-core/src/main/resources/ConvergenceLibrary/load-break-switch.svg
Bug fix
On a open load break switch, the horizontal line inside the rectangle is not completely drawn
=> Open load break switch svg error

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/NominalVoltageDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologicalStyleProvider.java, single-line-diagram-core/src/test/java/com/powsybl/sld/util/NominalVoltageStyleTest.java, single-line-diagram-core/src/test/java/com/powsybl/sld/util/TopologicalStyleTest.java, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/vl3.svg, single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl3_optimized.svg, single-line-diagram-core/src/test/resources/vlDiag_metadata.json, single-line-diagram-core/src/test/resources/zone.svg
No
Bug fix
Wire class names are not unique and are responsible for for coloration issue. 
Wire class names are unique, derived from prefixId + containerId + node 1 id + node 2 ide 
**Other …
=> Fix wire style class name unicity issue

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/vl3.svg, single-line-diagram-core/src/test/resources/vl3_optimized.svg, single-line-diagram-core/src/test/resources/zone.svg
Bug fix
When we run a load flow in Study-app, the change in the power flow values cause a svg resizing.
No svg resizing after a load flow.
(if any of the questions/checkboxes …
=> Avoid SVG resizing when power flow values change

single-line-diagram-core/src/main/java/com/powsybl/sld/library/ResourcesComponentLibrary.java, single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/AbstractTestCaseIidm.java
Signed-off-by: Florian Dupuy <florian.dupuy@rte-france.com>
No
Feature
The ResourcesComponentLibrary cannot contain components located in more than one folder.
The tests classes extending AbstractTestCase cannot properly specify another ResourcesComponentLibrary than the one in "/ConvergenceLibrary" 
**What is the new behavior (if this is a feature …
=> More than one directory for the resources component library

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java
The fictitious SwitchNodes were displayed even if showInternalNodes was set to false.
No
Bug fix
Fictitious SwitchNodes displayed even if showInternalNodes set to false.
Fictitious SwitchNodes not displayed when showInternalNodes set to false.
No
=> Correcting bug displaying fictitious SwitchNode

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_decorated.svg, single-line-diagram-core/src/test/resources/vl1_decorated_opt.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl1_straightWires.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/zone.svg
Issue #144 
Bug fix
Arrows misplaced if LayoutParameters.setDrawStraightWires(true)
Arrows placed correctly
No
=> Arrows straight wires

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/vl1_lpChanged.svg, single-line-diagram-core/src/test/resources/vl1_lpChanged_opt.svg, single-line-diagram-core/src/test/resources/vlDiag_metadata.json, single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java, single-line-diagram-view/src/main/java/com/powsybl/sld/view/AbstractContainerDiagramView.java, single-line-diagram-view/src/main/java/com/powsybl/sld/view/NodeHandler.java
Signed-off-by: Florian Dupuy <florian.dupuy@rte-france.com>
No
Feature
Not so easy to get the equipment name...
Mouse over to get the equipment name
firefox:
No
(if any of the questions/checkboxes don't apply, …
=> Add tooltip with equipment name

single-line-diagram-core/src/main/java/com/powsybl/sld/library/ResourcesComponentLibrary.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_decorated.svg, single-line-diagram-core/src/test/resources/vl1_decorated_opt.svg, single-line-diagram-core/src/test/resources/vl1_lpChanged.svg, single-line-diagram-core/src/test/resources/vl1_lpChanged_opt.svg, single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/vl3.svg, single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl3_optimized.svg, single-line-diagram-core/src/test/resources/zone.svg
Wrong indentation in svg diagram was because of the text nodes in the svg basic components. Indeed, empty text nodes were kept and the transformer does not manage them. This PR looks for empty nodes and delete them after loading each component. Another way would have been to validate the content of the svg component while loading it.
No
Bug fix
Wrong indentation in produced svg
**What is the new behavior (if this is …
=> Indentation

single-line-diagram-core/src/main/java/com/powsybl/sld/NetworkGraphBuilder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/BodyPrimaryBlock.java, single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.xml, single-line-diagram-core/src/test/resources/TestCase1BusBreaker.json
Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>
=> add missing fictitious nodes

single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologicalStyleProvider.java
Signed-off-by: NOIR Nicolas ext <nicolas.noir@rte-france.com>
No
This PR fixes a bug
Currently, some wires surrounding an open switch are not correctly colored (i.e. are not colored according to their voltage level)
Wires surrounding an open switch are now colored according to their voltage level. …
=> Modified edge color in case one of the extremities is an open switch

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramStyleProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/ElectricalNodeInfo.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java, single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase12GraphWith3WT.java, single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/vlDiag_metadata.json, single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java
Feature
No electrical nodes informations (voltage, angle) are displayed
Add optionnally a legend showing the different electrical nodes with their voltage and angle values, at the bottom of the diagram. …
=> Add optional legend for nodes with voltage and angle values

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_feeder_arrow_symmetry.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_decorated.svg, single-line-diagram-core/src/test/resources/vl1_decorated_opt.svg, single-line-diagram-core/src/test/resources/vl1_lpChanged.svg, single-line-diagram-core/src/test/resources/vl1_lpChanged_opt.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/vlDiag_metadata.json, single-line-diagram-core/src/test/resources/zone.svg, single-line-diagram-view-app/src/main/java/com/powsybl/sld/view/app/AbstractSingleLineDiagramViewer.java
Feature
Active power values are above reactive power values, if feeder cell direction is top
Active power values are below reactive power values, if feeder cell direction is bottom
Active power values are always above reactive power values, whatever the feeder cell direction is (top or bottom) …
=> Put active power values above reactive power values

single-line-diagram-core/src/main/resources/ConvergenceLibrary/svc.svg
No
Bug fix
Wrong height (12px) for svc component in components.xml and in svc.svg instead of 9px (and ugly arrow)
svg corrected to have height of 12px
**Does this PR introduce a breaking change or deprecate an API?** No
=> Correct static var compensator svg height

single-line-diagram-core/src/main/java/com/powsybl/sld/util/DomUtil.java
No
Bug fix
If a user of single-line-diagram is using Xalan 2.7.2 (latest version), or embeds another TransformerFactory or DocumentBuilderFactory which does not support ACCESS_EXTERNAL_DTD or ACCESS_EXTERNAL_STYLESHEET, creating the svg file will throw an exception
While waiting for a better solution to be found, the ACCESS_EXTERNAL_DTD and …
=> Remove setting the access external for XML parsing factories

pom.xml
No
Dependency cleanup
We depend on itextpdf through gephi which has an incompatible license.
itextpdf is not used and has been excluded.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
=> Clean Gephi dependencies

single-line-diagram-core/src/main/resources/baseVoltageConstantColors.css, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg
No
Bug fix
Breaker fill color is missing for TopologicalStyleProvider and NominalVoltageDiagramStyleProvider
Breaker fill color set to white for those DiagramStyleProviders
No
=> Correct breaker fill color missing

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase3TripleCoupling.java, single-line-diagram-core/src/test/resources/TestCase3TripleCoupling.json
No
Bug fix
When there are several vertical intern cells in a voltage level, their order is not stable (in particular it can be seen when changing disconnector state)
Stable ordering
No
=> Correct vertical intern cells instability

single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatus.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusAdder.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusAdderImpl.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusAdderImplProvider.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusImpl.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusXmlSerializer.java, single-line-diagram-iidm-extensions/src/main/resources/xsd/branchStatus.xsd, single-line-diagram-iidm-extensions/src/test/java/com/powsybl/sld/iidm/extensions/BranchStatusXmlTest.java, single-line-diagram-iidm-extensions/src/test/resources/branchStatusRef.xml
No
This PR introduces a new kind of extension, the BranchStatus. This extension allows to add a new status on a branch (or a three windings transformer). The possible values for this status are: "In operation", "Planned outage" and "Forced outage"
This will allow to clearly represent these three possible states of a branch on the single line diagram. …
=> Creation of a BranchStatus extension

.github/workflows/maven.yml
No
Bug fix / library update
actions checkout uses version 1.0.0
actions setup-java uses master version
CI stops when setting up JDK 11 with error message `Error: Input required and not supplied: distribution`
actions checkout uses [latest version 2.3.4](https://github.com/actions/checkout/releases/tag/v2.3.4)
actions setup-java uses [latest version …
=> Update actions to latest versions

pom.xml
No
Dependency fix
Guava is listed as a direct dependency of single-line-diagram, but is only inherited from powsybl-commons and powsybl-iidm-impl (plus jimfs for tests).
Guava removed from dependencies in pom.xml
No
As a consequence PR #227 will be closed.
=> Remove guava direct dependency

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/VoltageLevelLayoutFactorySmartSelector.java
The context classloader can be the wrong one (and ServiceLoader.load returns an empty list)
when you are calling ServiceLoader.load in the ForkJoinPool.commonPool() (or any other thread pool)
and you have your classes in another classloader than the AppClassLoader (=system classloader).
This is the case when using a springboot fat jar, or when deploying the code in a war in an application
server, or when using mvn exec:java
Signed-off-by: Jon Harper <jon.harper87@gmail.com> …
=> use ServiceLoader.load with the current classloader instead of the context classloader

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase13ZoneGraph.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestUnicityNodeIdWithMutipleNetwork.java, single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/vl1_external_css_no_import.svg, single-line-diagram-core/src/test/resources/vlDiag_metadata.json
No
Bug fix + feature
`cssInternal` parameter is missing in constructor and in copy constructor, and there is no way not to import css if external css is dealt by html
`cssInternal` boolean parameter is changed into `cssLocation` enum parameter (either `INSERTED_IN_SVG`, `EXTERNAL_IMPORTED` or `EXTERNAL_NO_IMPORT`). It is initialized in constructor and copied in copy constructor. `EXTERNAL_NO_IMPORT` allows not to import the external css. …
=> Change LayoutParameters cssInternal parameter

single-line-diagram-force-layout/src/main/java/com/powsybl/sld/force/layout/Spring.java
No
Bug fix
Force layout algorithm is not robust to duplicated edges
Force layout algorithm robust to duplicated edges
No
Duplicated edges in the force layout unit test. The force layout algorithm was diverging.
=> Force layout: avoid duplicating force in case of duplicated edge

single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractBaseGraph.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Edge.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/VoltageLevelGraph.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/resources/InternalBranchesBusBreaker.svg, single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusBusBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusNodeBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsSwitches.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_feeder_arrow_symmetry.svg, single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_external_css.svg, single-line-diagram-core/src/test/resources/vl1_external_css_no_import.svg, single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl1_straightWires.svg, single-line-diagram-core/src/test/resources/vl1_tooltip_opt.svg, single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/zone.svg
No, but simplifies rotation problem of issue #247 
Bug fix / refactor
3WT are drawn below the connecting lines, leading to overlapping
Labels are rotated on switches if node is rotated
Complex code used to handle rotation, and node rotation changed while drawing.
3WT drawn above connecting lines
Simpler code to handle rotation, which is now carried by subcomponent elements (like it was already done for 3wt), while translation is carried …
=> SVG draw refactor

single-line-diagram-core/src/main/java/com/powsybl/sld/util/TopologicalStyleProvider.java, single-line-diagram-core/src/test/java/com/powsybl/sld/util/TopologicalStyleTest.java
No
Bug fix
- TopologicalStyleProvider calculates the connected set for each node instead of calculating it once
- TopologicalStyleProvider calculations are based on a map of equipment ids, but nothing ensures that those equipment ids are unique and not null (see fictitious internal nodes, for which it doesn't really make sense)
- TopologicalStyleProvider does not recalculate the connected set if already known
- TopologicalStyleProvider …
=> TopologicalStyleProvider corrections

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramLabelProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramLabelProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/ElectricalNodeInfo.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/FeederInfo.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/GraphMetadata.java, single-line-diagram-core/src/test/java/com/powsybl/sld/raw/AbstractTestCaseRaw.java, single-line-diagram-core/src/test/java/com/powsybl/sld/svg/GraphMetadataTest.java
No
Parameter rename
Parameter intended for measure id (introduced in #290) is called userId, causing confusion with the id of an user
Parameter renamed to userDefinedId
No
=> Rename userId to userDefinedId

single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatus.java, single-line-diagram-iidm-extensions/src/main/java/com/powsybl/sld/iidm/extensions/BranchStatusImpl.java
=> Fix BranchStatus code smells

single-line-diagram-core/src/main/resources/ConvergenceLibrary/components.css, single-line-diagram-core/src/main/resources/tautologies.css, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSVGWriter.java, single-line-diagram-core/src/test/resources/InternalBranchesBusBreaker.svg, single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusBusBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusNodeBreaker.svg, single-line-diagram-core/src/test/resources/NodeDecoratorsSwitches.svg, single-line-diagram-core/src/test/resources/TestCase1.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosNominalVoltage.svg, single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram-core/src/test/resources/TestWithGreyFrameBackground.css, single-line-diagram-core/src/test/resources/label_on_all_nodes.svg, single-line-diagram-core/src/test/resources/substation.svg, single-line-diagram-core/src/test/resources/substation_feeder_arrow_symmetry.svg, single-line-diagram-core/src/test/resources/substation_no_feeder_values.svg, single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram-core/src/test/resources/vl1.svg, single-line-diagram-core/src/test/resources/vl1_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram-core/src/test/resources/vl1_straightWires.svg, single-line-diagram-core/src/test/resources/vl1_tooltip_opt.svg, single-line-diagram-core/src/test/resources/vl2.svg, single-line-diagram-core/src/test/resources/vl2_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram-core/src/test/resources/vl3.svg, single-line-diagram-core/src/test/resources/vl3_nominal_voltage_style.svg, single-line-diagram-core/src/test/resources/vl3_optimized.svg, single-line-diagram-core/src/test/resources/with_frame_background.svg, single-line-diagram-core/src/test/resources/zone.svg
No
Feature
sld-frame css definition is set to lightgrey and located into components.css
sld-frame css definition is still located into components.css as a variable and can be override by user
**Other …
=> Fix svg background

single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/main/java/com/powsybl/sld/cgmes/layout/CgmesZoneLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/RawGraphBuilder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/AbstractLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/CellBlockDecomposer.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ForceSubstationLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LBSCluster.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/VerticalSubstationLayout.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractBlock.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractCell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractComposedBlock.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractPrimaryBlock.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Block.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/BusNode.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Cell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/LegPrimaryBlock.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/Node.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/ShuntCell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/SubstationGraph.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramLabelProvider.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java
No
Refactor
Graph keyword is often used for VoltageLevelGraph (whose old name was Graph), making it ambiguous when calling getGraph
Graph keyword is used for Graph interface, VoltageLevelGraph keyword used instead when ambiguous
**Does this PR introduce a breaking change or deprecate an API?** **Yes**
=> Get voltage level graph

single-line-diagram-core/src/main/java/com/powsybl/sld/SingleLineDiagram.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSingleLineDiagramClass.java
No
Bug fix
A NullPointerException is thrown when the ID is not a valid network element.
A proper exception is thrown to explain that no element with such ID has been found
**Does this PR introduce a breaking change or deprecate an …
=> Fix NPE when element ID does not exist

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/GraphMetadata.java, single-line-diagram-core/src/test/java/com/powsybl/sld/svg/GraphMetadataTest.java, single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json, single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json, single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram-core/src/test/resources/vlDiag_metadata.json
Fixes #360 
Feature
In metadata, there are 2-3 parameters for each feederInfo:
- the id of the feeder info in the SVG
- the corresponding feeder node id (single-line-diagram internal id)
- the user defined id if non-null
In metadata, one should be able to get the equipment id corresponding to the feeder info, but also the side if it is a branch.
**Does this …
=> Replace feederNodeId by equipmentId + side in GraphMetadata

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphTraversal.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/ImplicitCellDetector.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/TopologyCalculation.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractBusCell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractCell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/ExternCell.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/InternCell.java, single-line-diagram-core/src/test/resources/TestCaseComplexCoupling.svg
No
Bug fix
Graph traversal uses
- one list for traversed nodes, hence creating duplicated nodes in some cases
- one list for visited nodes, hence affecting performance for large substations / voltage levels
Graph traversal uses
- one set for traversed nodes
- one set for visited nodes
No, the GraphTraversal methods signature is changed but it is an internal API
=> Use sets in graph traversal

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockOrganizer.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockPositionner.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactory.java, single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramLabelProvider.java, single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase15GraphWithVoltageIndicator.java, single-line-diagram-core/src/test/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactoryTest.java, single-line-diagram-core/src/test/resources/TestCase15GraphWithVoltageIndicator.svg, single-line-diagram-core/src/test/resources/TestCase15GraphWithVoltageIndicatorTopological.svg, single-line-diagram-core/src/test/resources/TestCase15GraphWithoutVoltageIndicator.svg
No
Feature
When addCellForBusInfo parameter of BlockOrganizer is set to true, one cell is adding on previous subsection only at right and left side
Replace addCellForBusInfo parameter of BlockOrganizer by a map (bus id / side) 
in order to add cell on previous subsection only at right or left side …
=> Adding one cell on previous subsection only at right or left side

single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
NO
Perf improvement
network.getBusView.getBus() computes the topology of the whole network
voltageLevel.getBusView.getBus() computes the topology of the voltage level
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
=> use voltageLevel.getBusView() instead of network.getBusView() to improve performance

single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java
Signed-off-by: Thomas ADAM <tadam@silicom.fr>
No
Feature
Debug files are written at user home .powsybl folder
Debug files are written at user home .powsybl/debug-sld folder
(if …
=> Add debug-sld folder into .powsybl to write debug files

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LegBusSet.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/cells/InternCell.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase3Coupling.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase3TripleCoupling.java, single-line-diagram-core/src/test/resources/TestCase3Coupling3Bars.json, single-line-diagram-core/src/test/resources/TestCase3Coupling3Bars2Sections.json
No
Bug fix
Shape missing on specific intern cells, leading to erroneous diagrams:
Shape added
No
=> Fix missing shape

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/AbstractPositionFinder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockOrganizer.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionFinder.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/PositionByClustering.java, single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionfromextension/PositionFromExtension.java, single-line-diagram-core/src/main/java/com/powsybl/sld/model/graphs/VoltageLevelGraph.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCaseMissingBusbarPosition.java, single-line-diagram-core/src/test/resources/TestCaseMissingBusbarPositionBusApart.json, single-line-diagram-core/src/test/resources/TestCaseMissingBusbarPositionBusParallel.json
No
Bug fix
When a busbar position extension is missing and `PositionFromExtension` is used as `PositionFinder`, then `BlockOrganizer` fails with an `ArrayOutOfBoundException`.
When a busbar position extension is missing and `PositionFromExtension` is used as `PositionFinder`, then we replace the missing indices with appropriate values: either with the same section index as the first busNode which shares a BusCell with, or if none with a new section index.
No
=> Fix missing busbar extension bug

single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockPositionner.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/CreateNetworksUtil.java, single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestFlatSection.java, single-line-diagram-core/src/test/resources/TestUndefinedBlockExternCell.json, single-line-diagram-core/src/test/resources/testFlatSections.json
No
Bug fix
Buses with no feeders nor couplers have a zero width:
Buses with no feeders nor couplers have a width of one cell:
No
=> Fix empty buses width

single-line-diagram-core/src/main/java/com/powsybl/sld/library/ComponentTypeName.java, single-line-diagram-core/src/main/java/com/powsybl/sld/util/AbstractBaseVoltageDiagramStyleProvider.java, single-line-diagram-core/src/test/resources/InternalBranchesBusBreaker.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHFirst.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHLast.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHMiddle.svg, single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHNone.svg, single-line-diagram-core/src/test/resources/TestCaseFictitiousBusTopological.svg
No
Bug fix
In the default StyleProvider implementation, the 2-winding transformers are detected to put the appropriate voltage level style:
- no voltage level style on the component itself
- voltage level style for each winding subcomponent 
This detection is based on 2-winding transformers component name with the use of a static method, which leaves no space for the custom 2-winding transformers.
In the default StyleProvider implementation, the detection of 2-winding transformers and more generally the nodes connecting two voltage …
=> Fix two-winding transformers static definition in style provider

single-line-diagram-core/src/main/java/com/powsybl/sld/builders/NetworkGraphBuilder.java, single-line-diagram-core/src/test/java/com/powsybl/sld/builders/NetworkGraphBuilderTest.java
No
Bug fix
Conductor or inductor symbol is made on current susceptance so dependent of the activated sections. In addition when no section is activated, a conductor is drawn.
The conductor or inductor choice is done only on …
=> Fix shunt compensator component type

single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram-core/src/test/resources/TestCase15GraphWithVoltageIndicator.svg, single-line-diagram-core/src/test/resources/TestCase15GraphWithVoltageIndicatorTopological.svg, single-line-diagram-core/src/test/resources/TestCase15GraphWithoutVoltageIndicator.svg, single-line-diagram-core/src/test/resources/TestCaseLoadBreakSwitch.svg, single-line-diagram-core/src/test/resources/consecutive_shunts.svg
No
Bug fix
When drawing cell bay all neighbouring edges are drawn, leading to some edges being drawn twice
When drawing cell bay only inside edges are drawn
No
=> Draw all edges once only

network-area-diagram/src/main/java/com/powsybl/nad/model/Graph.java, network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java, network-area-diagram/src/test/resources/3wt.svg, network-area-diagram/src/test/resources/3wt_disconnected.svg, network-area-diagram/src/test/resources/3wt_disconnected_topological.svg, network-area-diagram/src/test/resources/3wt_partial.svg, network-area-diagram/src/test/resources/edge_info_double_labels.svg
Feature
Not all edges of 3wt are written to the metadata (only the last one for each transformer).
The drawings for 3wt edges are not marked as stretchable.
All edges of 3wt are written to metadata. They have the same equipment identifier.
Drawings for these edges are marked as stretchable.
=> Add metadata for 3wt edges and nodes

network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java, network-area-diagram/src/test/resources/IEEE_118_bus.svg, network-area-diagram/src/test/resources/IEEE_118_bus_partial.svg, network-area-diagram/src/test/resources/IEEE_118_bus_partial_non_connected.svg, network-area-diagram/src/test/resources/IEEE_14_bus.svg, network-area-diagram/src/test/resources/IEEE_14_bus_disconnection.svg, network-area-diagram/src/test/resources/IEEE_14_bus_fictitious.svg, network-area-diagram/src/test/resources/IEEE_14_bus_text_nodes.svg, network-area-diagram/src/test/resources/IEEE_14_id_prefixed.svg, network-area-diagram/src/test/resources/IEEE_24_bus.svg, network-area-diagram/src/test/resources/IEEE_30_bus.svg, network-area-diagram/src/test/resources/IEEE_57_bus.svg, network-area-diagram/src/test/resources/current_limits.svg, network-area-diagram/src/test/resources/detailed_text_node.svg, network-area-diagram/src/test/resources/detailed_text_node_no_legend.svg, network-area-diagram/src/test/resources/diamond-spring-repulsion-factor-0.0.svg, network-area-diagram/src/test/resources/diamond-spring-repulsion-factor-0.2.svg, network-area-diagram/src/test/resources/edge_info_missing_label.svg, network-area-diagram/src/test/resources/edge_info_perpendicular_label.svg, network-area-diagram/src/test/resources/edge_info_shift.svg, network-area-diagram/src/test/resources/hvdc-vl-depth-1.svg, network-area-diagram/src/test/resources/hvdc.svg, network-area-diagram/src/test/resources/parallel_transformers.svg, network-area-diagram/src/test/resources/simple-eu-loop100.svg, network-area-diagram/src/test/resources/simple-eu-loop80.svg, network-area-diagram/src/test/resources/simple-eu.svg, network-area-diagram/src/test/resources/vl_description_id.svg, network-area-diagram/src/test/resources/vl_description_substation.svg, network-area-diagram/src/test/resources/vl_description_substation_id.svg, network-area-diagram/src/test/resources/voltage_limits.svg
Feature
Currently the drawings for half edges are only labelled as _stretchable_.
To handle updates of these drawings during user interaction (moving nodes) we need to label each edge half as _glued_ to the corresponding edge end, in addition to _stretchable_.
Every half edge is labelled as _stretchable_ and _glued_ to its corresponding end.
=> add glued class to half edge drawings

network-area-diagram/src/main/java/com/powsybl/nad/NetworkAreaDiagram.java
Change default StyleProvider in draw functions from NominalVoltageStyleProvider to TopologicalStyleProvider
Signed-off-by: Sophie Frasnedo <sophie.frasnedo@rte-france.com>
Feature
The default style provider is the NominalVoltageStyleProvider.
The default style provider is now the TopologicalStyleProvider.
=> Change default StyleProvider in draw functions

single-line-diagram/single-line-diagram-core/src/main/resources/FlatDesignLibrary/components.json, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11FlatDesign.svg
No
Bug fix
Thre are too many anchors on disconnectors in FlatDesignLibrary, leading to wrong anchor taken on forks.
Remove spurious anchors and add possible transformation for `MIDDLE` orientation
No
=> [SLD] Fix disconnector anchors in FlatDesignLibrary

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/GraphMetadata.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/svg/GraphMetadataTest.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/vlDiag_metadata.json
Signed-off-by: Sophie Frasnedo <sophie.frasnedo@rte-france.com>
#472
=> add field in feederinfo metadata

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionfromextension/PositionFromExtension.java
Yes, fixes #485
Bug fix / code clean
Warning on almost all extern cells, and twisted code when setting directions in PositionFromExtension
No warning if two directions in an extern cell if one of them is `UNDEFINED`, clarify code by refactoring and adding comment
No
=> [SLD] Fix set direction in bus cells

network-area-diagram/src/main/java/com/powsybl/nad/utils/iidm/IidmUtils.java, network-area-diagram/src/test/java/com/powsybl/nad/svg/DanglingLineTest.java, network-area-diagram/src/test/resources/dangling_line_connected.svg, network-area-diagram/src/test/resources/dangling_line_disconnected.svg
Bug fix
Drawings of disconnected dangling lines are painted with one half dashed and one half solid.
See the problem here:
A disconnected dangling line should be painted with both halves using the same style.
Solid when it is connected and dashed when it is disconnected.
See the fixed drawing for disconnected status:
This is the (correct) drawing when the dangling line is connected:
=> NAD : fix dangling line drawing disconnected status

pom.xml
No
Bug fix
powsybl-diagram-test is in test scope and is therefore not covered by tests according to sonar report
powsybl-diagram-test covered by tests as not in test scope anymore
No
Fixes #524 which was not correcting properly coverage computation
=> Fix cross-module coverage of diagram-test

network-area-diagram/pom.xml, pom.xml, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/pom.xml, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-iidm-extensions/pom.xml, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/pom.xml, single-line-diagram/single-line-diagram-core/pom.xml
Pom cleaning :
- No need for loadflow dependencies
- No need of powsybl-config-test (a com.google.common.jimfs dependency has been added directly in network-area-diagram whereas it was precedently pulled from powsybl-config-test) 
No
=> Remove loadflow dependencies and config-test dependencies

single-line-diagram/single-line-diagram-core/src/main/resources/highlightLineStates.css, single-line-diagram/single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusBusBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusNodeBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsSwitches.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestBatteries.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHFirst.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHLast.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHMiddle.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHNone.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseFictitiousBus.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseKeepFictitiousSwitchNode.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseRemoveFictitiousSwitchNode.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestComplexParallelLegsInternalPst.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestFormattingFeederInfos.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassSubstation.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassVl.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestUnknownLibrary.svg, single-line-diagram/single-line-diagram-core/src/test/resources/consecutive_shunts.svg, single-line-diagram/single-line-diagram-core/src/test/resources/feederInfoTest.svg, single-line-diagram/single-line-diagram-core/src/test/resources/noComponentsOnBus.svg, single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_substation.svg, single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_vl2.svg, single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_vl3.svg, single-line-diagram/single-line-diagram-core/src/test/resources/switchesOnBus.svg, single-line-diagram/single-line-diagram-core/src/test/resources/topological_style_substation.svg, single-line-diagram/single-line-diagram-core/src/test/resources/with_frame_background.svg
Bug fix
With the HighlightLineStateStyleProvider, when a line was disconnected on both sides, the line was supposed to be colored in black to show this. In practice, it was not the case, the style did not apply.
=> Fix line connection highlight

single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/main/java/com/powsybl/sld/cgmes/dl/conversion/Transformer3WDiagramDataExporter.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/BusDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/BusbarDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/DanglingLineDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/GeneratorDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/HvdcLineDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/LineDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/LoadDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/ShuntDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/SvcDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/SwitchDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/Transformer3WDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-dl-conversion/src/test/java/com/powsybl/sld/cgmes/dl/conversion/exporters/TransformerDiagramDataExporterTest.java, single-line-diagram/single-line-diagram-cgmes/single-line-diagram-cgmes-layout/src/test/java/com/powsybl/sld/cgmes/layout/BusTopologyTest.java
No
Quality
Some deprecated methods (which will be removed in the next `powsybl-core` release) are used used.
This calls are replaced by their not-deprecated counterpart.
=> Replace deprecated methods usages

diagram-test/src/main/java/com/powsybl/diagram/test/Networks.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/GraphMetadata.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase11SubstationGraph.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/svg/GraphMetadataTest.java, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_with_hvdc_line_metadata.json
No
Feature
In node metadata for VSC or LCC contains fields id & equipmentId.
But the field id is "ascii-encoded" & equipmentId is the HVDC line id.
Add in metadata the LCC or VSC id.
=> LCC & VSC : add escaped id in metadata

single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestSingleLineDiagramClass.java
Quality
A function was added to allow Java 11 and Java 17 support.
Since we have moved to Java 17, this function is no longer necessary.
=> Delete fixSvg function since migrating to Java 17

network-area-diagram/src/main/java/com/powsybl/nad/NetworkAreaDiagram.java, network-area-diagram/src/main/java/com/powsybl/nad/build/iidm/NetworkGraphBuilder.java, network-area-diagram/src/test/java/com/powsybl/nad/NetworkAreaDiagramTest.java
=> [NAD] List of displayed voltage levels as an output

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LegBusSet.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/Subsection.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/positionbyclustering/PositionByClustering.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCaseExternCellOnTwoSections.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseExternCellOnTwoSections.svg
No
Bug fix
When an extern cell is on two busbars A & B with same busbar index the resulting diagram is completely wrong: one of the two busbars (say A) loses all its cells on the layout hence on the displayed svg, leading to the following dangerous consequences:
- the problematic extern cell is displayed as if it were only on busbar B
- all the extern cells of A are displayed on B
- the intern cell between A & B are displayed as if they were solely on B
While waiting for a better solution which would need a lot of work, such …
=> Detect inconsistent busNodes positions

network-area-diagram/src/main/java/com/powsybl/nad/build/iidm/VoltageLevelFilter.java, network-area-diagram/src/test/java/com/powsybl/nad/NetworkAreaDiagramTest.java, network-area-diagram/src/test/resources/IEEE_14_bus_voltage_filter4.svg, network-area-diagram/src/test/resources/IEEE_14_bus_voltage_filter5.svg
No
Feature
It is not possible to use a nominal voltage filter on NAD with no voltage level id list.
It is possible to use a nominal voltage filter with no voltage level id list.
=> Nominal voltage filter on whole network

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/MatrixZoneLayout.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/zonebygrid/Matrix.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/zonebygrid/MatrixZoneLayoutModel.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestCase13ZoneGraph.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase12ZoneGraphHHRaw.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase12ZoneGraphHVRaw.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase12ZoneGraphVHRaw.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase12ZoneGraphVVRaw.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphHH.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphHV.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphMatrix2x3.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphVH.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphVV.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_with_hvdc_line_metadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/vlDiag_metadata.json
No
Bug fix
Diagram padding is no taking into account in Zone Matrix Layout
Diagram padding is taking into account in Zone Matrix Layout
=> Matrix zone layout : fix diagram padding usage

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/builders/NetworkGraphBuilder.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphRefiner.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactory.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactoryParameters.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/model/graphs/NodeFactory.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/model/graphs/VoltageLevelGraph.java, single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/model/nodes/Internal2WTNode.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestInternalBranchesNodeBreaker.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactoryParametersTest.java, single-line-diagram/single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker_externalPst.svg
No
Bug fix / feature
Internal two-winding transformers and phase-shift transformers are added in VoltageLevelGraph as `EquipmentNode`s, hence are withing an InternCell or ExternCell.
Internal two-winding transformers and phase-shift transformers are added in VoltageLevelGraph as `FeederNode`s, but can be later replaced by `EquipmentNode`s with VoltageLevelLayoutFactoryParameter::setSubstituteInternalMiddle2wtByEquipmentNodes`. This parameter is true by default.
`NetworkGraphBuilder::handleConnectedComponents` …
=> Add parameter to disable/enable internal 2wt

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/LayoutParameters.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/layout/LayoutParametersTest.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassSubstationMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassVlMetadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_metadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/substDiag_with_hvdc_line_metadata.json, single-line-diagram/single-line-diagram-core/src/test/resources/vlDiag_metadata.json
Quality
This PR removes an unused parameter in the `LayoutParameters` class.
Previously, the `PathFinderType` (the algorithm used to draw the snakelines between substations in multi-substations diagrams) was an attribute of the `LayoutParameters` class and it was not easily customizable. 
This approach was replaced by another one (using a `ZoneLayoutPathFinderFactory` attribute in the `SldParameters` class) but the attribute `PathFinderType` was kept by mistake in `LayoutParameters`.
=> Remove pathfinder layoutparameters

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/iidm/HighlightLineStateStyleProvider.java, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseFictitiousBus.svg
No
Bug fix
All fictitious busNode are displayed as disconnected as they always carry the class sld-bus-disconnected
Fictitious busNode are never displayed as disconnected
=> Fix bug on fictitious busNodes

pom.xml
No
Dependency update
powsybl-diagram uses powsybl-parent v15.
powsybl-diagram uses powsybl-parent **v20**.
=> Bump powsybl-parent to v20

network-area-diagram/src/main/java/com/powsybl/nad/layout/AbstractLayout.java, network-area-diagram/src/main/java/com/powsybl/nad/layout/FixedLayoutFactory.java, network-area-diagram/src/main/java/com/powsybl/nad/layout/FixedLayoutFactoryUtils.java, network-area-diagram/src/main/java/com/powsybl/nad/layout/LayoutFactoryUtils.java, network-area-diagram/src/main/java/com/powsybl/nad/layout/TextPosition.java, network-area-diagram/src/main/java/com/powsybl/nad/svg/metadata/DiagramMetadata.java, network-area-diagram/src/main/java/com/powsybl/nad/svg/metadata/NodeMetadata.java, network-area-diagram/src/main/java/com/powsybl/nad/svg/metadata/TextNodeMetadata.java, network-area-diagram/src/test/java/com/powsybl/nad/layout/FixedLayoutTest.java, network-area-diagram/src/test/resources/two-voltage-levels_metadata.json
no
feature
In network area diagram initial positions of nodes and text nodes for a layout can be set providing them in maps
Initial positions of nodes and text nodes for a layout can be set reading them from a JSON diagram metadata file
=> Set layout node positions getting them from JSON metadata in network area diagram

network-area-diagram/src/main/resources/customStyle.css, network-area-diagram/src/test/resources/custom_style_provider.svg, network-area-diagram/src/test/resources/custom_style_provider_empty.svg
no
fix
there could be some style-overriding issues, with NADs - e.g., when multiple diagrams are in the same html page
and the last one happens to use the custom style.
in the customStyle.css: we keep the var(--nad-vl-color,  DEFAULT_VALUE) approach used in the other stylesheets, to prevent the issue. …
=> custom stylesheet fixes

network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java, network-area-diagram/src/main/java/com/powsybl/nad/svg/iidm/DefaultLabelProvider.java, network-area-diagram/src/test/java/com/powsybl/nad/svg/CustomLabelProviderTest.java, network-area-diagram/src/test/java/com/powsybl/nad/svg/TextNodeTest.java, network-area-diagram/src/test/resources/3wt_disconnected.svg, network-area-diagram/src/test/resources/3wt_disconnected_topological.svg, network-area-diagram/src/test/resources/IEEE_14_bus_disconnection.svg, network-area-diagram/src/test/resources/vl_description_id.svg
Fixes #680
Removes some NAD SVG parameters checking from the SvgWriter. The parameters involved are:
- edgeNameDisplayed (label along the branch edges)
- voltageLevelDetails (VL info box content)
- busLegend  (VL info box content)
The idea behind this PR is that the interpretation of those parameters should be a LabelProvider implementation's responsibility.
The DefaultLabelProvider has been changed, accordingly. The CustomLabelProvider simply ignores them (the content it provides is driven by the maps in its constructor, only).
Also in this PR: the simple rendering mode for the VL text nodes (i.e. the simple label) is removed from the SvgWriter. Now the detailed rendering …
=> moves some svg pars checking from writer to the labelprovider impl

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/iidm/TopologicalStyleProvider.java, single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/AbstractTestCase.java, single-line-diagram/single-line-diagram-core/src/test/resources/CustomLabelProviderTest1.svg, single-line-diagram/single-line-diagram-core/src/test/resources/GroundDisconnectorsAndGround.svg, single-line-diagram/single-line-diagram-core/src/test/resources/GroundDisconnectorsAndGroundFlat.svg, single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusBusBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestBatteries.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestBusBarOverVoltageLimitHightlight.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestBusBarUnderVoltageLimitHightlight.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseBusBreakerBusConnected.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseComplexExternCellOnFourSections.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseComplexExternCellOnTwoSections.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseLoadBreakSwitch.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseNodeBreakerBbsConnected.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestComplexParallelLegsInternalPst.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestInternCellDifferentSubsections.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestOneLegInternCellDifferentSubsectionsLbs.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestOneLegInternCellDifferentSubsectionsSi.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestTieLineSubstation.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestTieLineSubstationUnifiedColors.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestTieLineVoltageLevel.svg, single-line-diagram/single-line-diagram-core/src/test/resources/TestUnknownLibrary.svg, single-line-diagram/single-line-diagram-core/src/test/resources/VerticalInternalPstBranchStatusNodeBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/consecutive_shunts.svg, single-line-diagram/single-line-diagram-core/src/test/resources/disconnectedComponentsBusBreaker.svg, single-line-diagram/single-line-diagram-core/src/test/resources/topological_style_substation.svg
No
Bug fix
With TopologicalStyleProvider, circle in bus legend info is black instead of the bus color 
Circle in bus legend info takes the colour of the corresponding bus
=> [SLD] Fix missing style class for bus legend

single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultSVGWriter.java, single-line-diagram/single-line-diagram-core/src/test/resources/substation_optimized.svg, single-line-diagram/single-line-diagram-core/src/test/resources/vl1_multiline_tooltip.svg, single-line-diagram/single-line-diagram-core/src/test/resources/vl1_optimized.svg, single-line-diagram/single-line-diagram-core/src/test/resources/vl2_optimized.svg, single-line-diagram/single-line-diagram-core/src/test/resources/vl3_optimized.svg
No
Bug fix
Optimized SVG are broken (due to #700 escaping id)
Optimized SVG are back: we do not escape the provided component types, as the user has control over it (and the default component types include only allowed characters) 
=> [SLD] Fix optimized svg
